# Generated by Django 2.2 on 2022-02-16 08:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.AutoField(help_text='id', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.IntegerField(default=datetime.datetime.now, help_text='创建时间', verbose_name='创建时间')),
                ('req_url', models.URLField(help_text='请求url', verbose_name='请求url')),
                ('req_method', models.SmallIntegerField(help_text='请求方式', verbose_name='请求方式')),
                ('req_query', models.TextField(help_text='请求参数', verbose_name='请求参数')),
                ('req_body', models.TextField(help_text='请求body', verbose_name='请求body')),
                ('req_ip', models.CharField(help_text='请求IP', max_length=32, verbose_name='请求IP')),
                ('resp_body', models.TextField(help_text='响应body', verbose_name='响应body')),
                ('resp_status_code', models.SmallIntegerField(help_text='响应状态码', verbose_name='响应状态码')),
                ('resp_time', models.IntegerField(help_text='请求耗时', verbose_name='请求耗时')),
                ('req_user', models.ForeignKey(help_text='访问者', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='访问者')),
            ],
            options={
                'verbose_name': '访问日志',
                'verbose_name_plural': '访问日志',
                'db_table': 'access_log',
            },
        ),
    ]
